---
title: "lmer_tweets"
author: "Jana Lasser"
date: "2022-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r imports}
library(lme4)
library(lmerTest)
library(car)
library(sjPlot)
```

```{r read data}
tweets <- read.csv("../../data/tweets_for_lme_modelling.csv", colClasses=c("author_id"="character"))
```


```{r full model NewsGuard}
model_NG <- lmer(NG ~ 1 + belief * truth + belief * truth * party + (1 + belief * truth|author_id), data=tweets, control=lmerControl(optCtrl=list(maxfun=30000,algorithm="NLOPT_LN_NELDERMEAD") ))
```

```{r full model accuracy}
model_acc <- lmer(accuracy ~ 1 + belief * truth + belief * truth * party + (1 + belief * truth|author_id), data=tweets, control=lmerControl(optCtrl=list(maxfun=30000,algorithm="NLOPT_LN_NELDERMEAD") ))
```

```{r full model transparency}
model_trans <- lmer(transparency ~ 1 + belief * truth + belief * truth * party + (1 + belief * truth|author_id), data=tweets, control=lmerControl(optCtrl=list(maxfun=30000,algorithm="NLOPT_LN_NELDERMEAD") ))
```

```{r}
 saveRDS(model_NG, file = "lme_model_with_threeway_inderaction.rds")
```

```{r statistics NG model}
summary(model_NG)
```
```{r statistics NG model}
 tab_model(model_NG, show.aic=TRUE, show.loglik=TRUE, digits=4)
```
```{r statistics NG model}
BIC(model_NG)
```

```{r statistics accuracy model}
summary(model_acc)
```
```{r}
 tab_model(model_acc, show.aic=TRUE, show.loglik=TRUE, digits=4)
```
```{r}
BIC(model_acc)
```

```{r}
summary(model_trans)
```
```{r}
 tab_model(model_trans, show.aic=TRUE, show.loglik=TRUE, digits=4)
```
```{r}
BIC(model_trans)
```




